### ISSUE TITLE
Show UTXO state stats

### ISSUE THREAD

**Issue by A60AB5450353F40E** [melroy89/mempool#1]
The UTXO state is our most important metric since it's the scaling bottleneck and also can be a surrogate for our number of holders count, however I haven't found a good place where to watch its stats.

For BTC, I found that there is this: https://www.blockchain.com/es/explorer/charts/utxo-count but they don't have the same chart for BCH.

Suggestion:

- Chart showing (time, utxo count)
- Chart showing (time, total utxo state size)
- Chart showing (time, median utxo size)

**Comment by melroy89** [comment]
Thx. Created here: https://gitlab.melroy.org/bitcoincash/explorer/-/issues/2
